### ISSUE TITLE
pykotorcli is an ELF binary in the Mac release

### ISSUE THREAD

**Issue by Paisseon** [th3w1zard1/KOTORModSync#26]
Saw your comment on my issue in PyKotor so decided to check this out, but I'm getting an error on macOS 13.5, arm64. Weird permissions error aside (`chmod 0755` and disabling Gatekeeper fixes that) and it succeeded on JC's Minor Fixes, but failed on Character Startup Changes due to not being able to execute the pykotorcli file. Error message: `[Error] FAILED Instruction #2 Action 'TSLPatcher'`

The pykotorcli file is an ELF binary for Linux, not Mach-O binary as is used on macOS. This should be a pretty easy fix, but I'm not sure how to compile the pykotorcli from your PyKotor fork into a binary.

**Comment by th3w1zard1** [comment]
Ah, I see. Frankly I was hoping the linux binary would work as is on mac as they're both Unix, but I see that isn't the case.

I don't have a Mac, and I'm not sure how I can build the necessary pykotorcli binary without it. There are services such as MacStadium available as cloud providers for this kind of thing but I just haven't had time to look into it.

The easiest ways to get this working on Mac is to do one of the following:

1. Install pyinstaller by following [these instructions](https://pyinstaller.org/en/stable/installation.html). Then, fork over PyKotor from https://github.com/th3w1zard1/PyKotor.
Then, in a terminal, run the command:
 `pyinstaller --console --onefile pykotorcli.py`.
And that's it! This should create the binary you need in the `PyKotor\dist` directory.

2. Create a shell script in the KOTORModSync 'Resources' directory named 'pykotorcli', without any extension. This will be used as a proxy. Then, write a script to pass any command-line arguments directly to PyKotorCLI.py which you can download from my fork at https://github.com/th3w1zard1/PyKotor

If those aren't an option for you, the last solution I have is a bit tedious. In the TOML instructions file you've downloaded, modify all instances of `Action = TSLPatcher` to `Action = Execute`, then modify the `Arguments` to work with the pykotorcli.py directly. The `Source` field is the actual command to execute (something like `python pykotorcli.py`. The `Arguments` field would be the literal string `<<kotorDirectory>> <<modDirectory>>\\path\\to\\tslpatchdata's parent folder namespace_option_index`. You'd need to do this for every instruction.

Please keep me updated, I'd very much like to nail in Mac support in an upcoming release.

PS: If you get any ModuleNotFound errors while running pykotorcli, or while compiling it with pyinstaller, you can simply pip install the module it names. IIRC you need Ply and chardet which can be installed like `pip install chardet`. Everything else can be installed from `pip install -r requirements.txt` like the main PyKotor page explains.

**Comment by Paisseon** [comment]
Working now, thanks! Here's the Mac-compiled binary (zipped for GH upload) if you want to add it to the release 
[pykotorcli.zip](https://github.com/th3w1zard1/KOTORModSync/files/12443475/pykotorcli.zip)

**Comment by th3w1zard1** [comment]
Fantastic! I'm glad you got this working! :smile:

I'm going to reopen this issue as I think it'll be an ongoing issue

**Comment by th3w1zard1** [comment]
Fixed by v0.10.23
