### ISSUE TITLE
More options for installation of certain mods in build?

### ISSUE THREAD

**Issue by Domino5555** [th3w1zard1/KOTORModSync#36]
For example, could you make options available for which lore-accurate Mandalore mask can be installed, given that Snigaroo recommended the all-silver version?

**Comment by iMakedonsky** [comment]
@Domino5555 You can add your mods on top of base build easily. Just check how instructions are written for other mods and repeat them.

I've made a build with 7 extra mods on top of base build like that.

**Comment by th3w1zard1** [comment]
Keeping the TOMLs up-to-date is not within the scope of this issue board, this issue board is here to report bugs or request features in the overall modsync app itself.

That said I'll take a look when I have some free time.
