### ISSUE TITLE
'Some components failed to validate'

### ISSUE THREAD

**Issue by BlindWorship** [th3w1zard1/KOTORModSync#37]
So it was working previously but I think i accidently had swapped the directories around initially and started an install but then later exited out of it to fix it but now it won't read the files within the KOTOR 1 Full Build folder directory. I've tried deleting/reinstalling ModSync as well as restarting my computer and it won't validate anymore

![image](https://github.com/th3w1zard1/KOTORModSync/assets/88711497/70c3c2a5-43ae-4352-b26d-ac57e38b8ef9)
![image](https://github.com/th3w1zard1/KOTORModSync/assets/88711497/b77429a3-1417-42b6-b808-fd839bf8ee83)
![image](https://github.com/th3w1zard1/KOTORModSync/assets/88711497/ddf6ff43-6677-453e-8342-953852ac72c2)

**Comment by th3w1zard1** [comment]
Check the logs, console window, or output window, and either download the mods it's complaining about or deselect them so they won't be installed.

**Comment by th3w1zard1** [comment]
deleting/restarting won't do anything, you probably selected a mod you didn't have selected last time. The output isn't too terrible to read, look at the exact archive it's complaining about and either deselect that mod or go download it.
