### ISSUE TITLE
Missing Required Archives

### ISSUE THREAD

**Issue by Fuziius** [th3w1zard1/KOTORModSync#41]
Hello,

first of all, thanks for KOTORModSync. Without I wouldn't even trying to mod and play the game.

I downloaded "KOTOR1_Full.toml" and all mods from "[KOTOR 1 Full Build](https://kotor.neocities.org/modding/mod_builds/k1/full)".

In the first png there are two errors about missing required archives. The "Scoundrel" one doesn't even show up in the build list expect it should be the "Scoundrel Trousers" mod. But this one is in the mod folder. The "Senni Vek Restoration" one was downloaded but it's current name is "SVR1.2.7z".

In the second png are the errors that occur after I tried re-archiving the content from "SVR1.2.7z" as "Senni Vek Restoration.zip".

Also I noticed that following mods are unchecked by default at the "Available Mods" on the left side at the KOTORModSync when loading the "KOTOR1_Full.toml" file:
- Bastila Shan HD
- HD Carth Onasi
- HD Canderous Ordo
- K1 Melee Texture Enhancement
- Carth Onasi and Male PC Romance
- JC´s Romance Enhancement: Pan-Galactic Flirting for K1
- JC´s Romance Enhancement: Biromantic Bastila for K1

Can you help me getting rid from the errors at the "Pre-Install Validation"?
Can I leave the mods unchecked which are by default?

PS.: The linked video for the optional widescreen patch at the mod build list "[KOTOR 1 Full](https://kotor.neocities.org/modding/mod_builds/k1/full)" is the one from 8 years ago and not the updated video from 4 months ago.
![KOTOR1 Error before re-archiving](https://github.com/th3w1zard1/KOTORModSync/assets/115624975/27ecd149-6091-48ec-be90-7827729cfcc0)
![KOTOR1 Error after re-archiving with correct name](https://github.com/th3w1zard1/KOTORModSync/assets/115624975/7472cbea-f46a-45e5-a681-240980a45641)

**Comment by th3w1zard1** [comment]
https://github.com/th3w1zard1/KOTORModSync/issues/37

**Comment by th3w1zard1** [comment]
This issue board exists for issues with the main application, not the instructions/archives. The errors are telling you to download the correct archive, or deselect the mod if you don't want to download them.

**Comment by th3w1zard1** [comment]
> Can I leave the mods unchecked which are by default?

That is up to you: the player. Determine what you actually want to install, that is why the checkboxes exist
